### ISSUE TITLE
build fails with pidgin 2.7.9 on Centos

### ISSUE THREAD

**Issue by lahmann** [lunaskyrise/pidgin-irc-console#1]
Thanks a lot for this plugin, unfortunately building the plugin with Pidgin 2.7.9 and gcc 4.4.7 fails:

    irc-console.c: In function 'create_console':
    irc-console.c:423: error: implicit declaration of function 'pidgin_make_scrollable'
    irc-console.c:425: warning: passing argument 2 of 'gtk_box_pack_start' makes pointer from integer  without a cast
    /usr/include/gtk-2.0/gtk/gtkbox.h:84: note: expected 'struct GtkWidget *' but argument is of type 'int'
    irc-console.c:433: warning: assignment makes pointer from integer without a cast
    make: *** [irc-console.so] Error 1

**Comment by lunaskyrise** [comment]
https://developer.pidgin.im/ticket/10599
pidgin_make_scrollable requires Pidgin 2.8+, AFAIK.
